theWaster/account/urls.py
from django.conf.urls import url

from account import views


urlpatterns = [
    url(r'^$', views.login, name='login'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^register/$', views.register, name='register'),
]

theWaster/chat/urls.py
from django.conf.urls import url

from chat import views


urlpatterns = [
    url(r'^$', views.chat, name='chat'),
]

theWaster/edition/urls.py
from django.conf.urls import url

from edition import views


urlpatterns = [
    url(r'^$', views.sortEdition, name='sortEdition'),
    
    url(r'^sortCreate/$', views.sortCreate, name='sortCreate'), 
    url(r'^editionCreate/$', views.editionCreate, name='editionCreate'),
    url(r'^articleCreate/$', views.articleCreate, name='articleCreate'),

    
    url(r'^sortUpdate/(?P<sortId>[0-9]+)/$', views.sortUpdate, name='sortUpdate'),
    url(r'^editionUpdate/(?P<editionId>[0-9]+)/$', views.editionUpdate, name='editionUpdate'),


    url(r'^article/(?P<editionId>[0-9]+)/$', views.article, name='article'),
]

theWaster/main/urls.py
from django.conf.urls import url

from main import views


urlpatterns = [
    url(r'^$', views.main, name='main'),
    url(r'^templates/$', views.templates, name='templates'),
]

theWaster/theWaster/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^chat/', include('chat.urls', namespace='chat')),
    url(r'^edition/', include('edition.urls', namespace='edition')),
    url(r'^game/', include('game.urls', namespace='game')),
    url(r'^main/', include('main.urls', namespace='main')),
    url(r'^.*', include('account.urls')),
]
    
    
    
    

theWaster/main/models.py
from django.db import models

# Create your models here.

theWaster/main/views.py
from django.shortcuts import render
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

from main.constants import NUM_ITEMS_PER_PAGE

def main(request): 
    context = {} 
    return render(request, 'main/main.html', context) 


def templates(request): 
    return render(request, 'main/templates.html') 


def pagination(request, queryset, numItemsPerPage=NUM_ITEMS_PER_PAGE):   
    paginator = Paginator(queryset, numItemsPerPage)
    page = request.GET.get('page')
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        queryset = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        queryset = paginator.page(paginator.num_pages)
    
    fullPath = request.get_full_path()
    if fullPath.find('?') < 0:    # No search terms: add a question mark so that 'page' may be appended
        fullPath += '?'
    else:    # There are search terms
        index = fullPath.find('page')
        if index < 0:        # No 'page': add an '&' so that 'page' may be appended
            fullPath += '&'
        else:                # There is 'page': remove 'page' info
            fullPath = fullPath[:index]
            
    return {'queryset':queryset, 'paginator':paginator, 'fullPath':fullPath}

theWaster/main/templates/main/main.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>theWaster</title>
<meta charset=utf-8>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
<link rel=stylesheet href=https://cdnjs.cloudflare.com/ajax/libs/jquery-ui-timepicker-addon/1.6.3/jquery-ui-timepicker-addon.css>
<link rel="stylesheet" href="{% static 'main/css/main.css' %}">
<link rel="stylesheet" href="{% static 'main/css/form.css' %}">
<link rel="stylesheet" href="{% static 'main/css/misc.css' %}">
</head>
<body>
  <div id="logo">
    <img src="{% static 'main/img/theWaster.gif' %}">
  </div>
  
  <div id="bullectin" class='width60 floatLeft'>
    <h2>公告:</h2>
    <ul>
      <li>是公告</li>
      <li>是公告是公告是公告</li>
      <li>是公告</li>
    </ul>
  </div>
  
  <div id="mainform" class='width40 floatLeft form' >
  {% block forms %}{% endblock %}
  </div>
  <!-- try -->
  <div class=clear></div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
<script src="{% static 'main/js/fullDiv.js' %}"></script>
</body>
</html>

theWaster/main/templates/main/templates.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>theWaster</title>
<meta charset=utf-8>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
<link rel=stylesheet href=https://cdnjs.cloudflare.com/ajax/libs/jquery-ui-timepicker-addon/1.6.3/jquery-ui-timepicker-addon.css>
<link rel="stylesheet"  href="{% static 'main/css/reset.css' %}">
<link rel="stylesheet"  href="{% static 'main/css/normalize.css' %}">
<link rel="stylesheet" href="{% static 'main/css/main.css' %}">
<link rel="stylesheet"  href="{% static 'main/css/menu.css' %}">
<link rel="stylesheet"  href="{% static 'main/css/messages.css' %}">
<link rel="stylesheet" href="{% static 'main/css/button.css' %}">
<link rel="stylesheet" href="{% static 'main/css/pagination.css' %}">
<link rel="stylesheet" href="{% static 'main/css/form.css' %}">
<link rel="stylesheet" href="{% static 'main/css/search.css' %}">
<link rel="stylesheet" href="{% static 'main/css/table.css' %}">
<link rel="stylesheet" href="{% static 'main/css/misc.css' %}">
{% block css %}{% endblock %}
</head>
<body>
  <header>
    <div class=logo>
      <a href="{% url 'main:templates' %}"><img src="{% static 'main/img/logo2.png' %}"></a>
    </div>
    <ul class="menu">
      <li><a href=#> 聊聊</a></li>
      <li id=part><a href=#> 帖子</a></li>
      <li id=game><a href=#> 遊戲</a></li>
    </ul>
    <ul class=account>
      <li><a class=accountIcon href=#></a></li>
      <li><a class=logout href="{% url 'account:logout' %}"></a></li>
    </ul>
    <div class=clear></div>
  </header>
  <div id=son class=partson>
  {% for sort in SORT %}
    <ul>
    <p>{{ sort.sort }}</p>
      {% for edition in EDITION %}
        {% if edition.sort == sort %}
        <li><a href={% url 'edition:article' edition.id %}>{{ edition.edition }}</a></li>
        {% endif %}
      {% endfor %}
      </ul>
  {% endfor %}    
    <div class=clear></div>
  </div>
  <div id=son class=gameson>
    <div class=clear></div>
  </div>
  
  <div id=content>{% block content %}{% endblock %}</div>
  
  <footer>
  <ul>
  <li><a href=#> 聯絡我們</a></li>
  <li><a href=#> Q&A</a></li>
  </ul>
  <p>@ ailan12345, ballfish, shunmao</p>
  </footer>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
<script src="{% static 'main/js/mouseover.js' %}"></script>
<script src="{% static 'main/js/menuson.js' %}"></script>
{% block script %}{% endblock %}
  
</body>
</html>