theWaster/chat/urls.py
from django.conf.urls import url

from chat import views


urlpatterns = [
    url(r'^$', views.chat, name='chat'),
]

theWaster/edition/urls.py
from django.conf.urls import url

from edition import views


urlpatterns = [
    url(r'^$', views.sortEdition, name='sortEdition'),
    
    url(r'^sortCreate/$', views.sortCreate, name='sortCreate'), 
    url(r'^editionCreate/$', views.editionCreate, name='editionCreate'),
    url(r'^articleCreate/$', views.articleCreate, name='articleCreate'),

    
    url(r'^sortUpdate/(?P<sortId>[0-9]+)/$', views.sortUpdate, name='sortUpdate'),
    url(r'^editionUpdate/(?P<editionId>[0-9]+)/$', views.editionUpdate, name='editionUpdate'),


    url(r'^article/(?P<editionId>[0-9]+)/$', views.article, name='article'),
]

theWaster/theWaster/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^chat/', include('chat.urls', namespace='chat')),
    url(r'^edition/', include('edition.urls', namespace='edition')),
    url(r'^game/', include('game.urls', namespace='game')),
    url(r'^main/', include('main.urls', namespace='main')),
    url(r'^.*', include('account.urls')),
]
    
    
    
    

theWaster/edition/models.py
from django.contrib.auth.models import User
from django.db import models

from account.models import UserProfile


class Sort(models.Model):
    sort = models.CharField(max_length=128) #類別
    disabled = models.BooleanField(default=False) #啟用停用
    
    def __str__(self):
        return self.sort

class Edition(models.Model):
    sort = models.ForeignKey(Sort) 
    edition = models.CharField(max_length=128) #版名
    user = models.ManyToManyField(User)  #板主
    disabled = models.BooleanField(default=False) #啟用停用

    def __str__(self):
        return self.edition
    
    
class Article(models.Model):
    edition = models.ForeignKey(Edition)
    user = models.ForeignKey(User, related_name='Po') #發文者
    title = models.CharField(max_length=128) #標題
    content = models.TextField() #內容
    dateTime = models.DateTimeField() #發表時間
    bad = models.ManyToManyField(User) #廢

    def __str__(self):
        return self.title


class Comment(models.Model):
    article = models.ForeignKey(Article) 
    user =   models.ForeignKey(User, related_name='PoC') #留言者
    content = models.TextField() #內容
    dateTime = models.DateTimeField() #留言時間
    bad = models.ManyToManyField(User) #廢

    def __str__(self):
        return self.content                
                

theWaster/edition/forms.py
from django import forms 
from django.contrib.auth.models import User

from edition.models import Edition, Sort, Article, Comment


class SortForm(forms.ModelForm):
    sort = forms.CharField(label='類別', max_length=64)
    disabled = forms.ChoiceField(label='啟用停用', choices=((True,'啟用'),(False,'停用')),  widget = forms.RadioSelect())


    class Meta: 
        model = Sort
        fields = '__all__'


class EditionForm(forms.ModelForm): 
    sort = forms.ModelChoiceField(label='類別',queryset=Sort.objects.all())
    edition = forms.CharField(label='版名', max_length=128)
    user = forms.ModelMultipleChoiceField(label='板主', queryset=User.objects.all()) 
    disabled = forms.ChoiceField(label='啟用停用', choices=((True,'啟用'),(False,'停用')),  widget = forms.RadioSelect())


    class Meta: 
        model = Edition 
        fields = '__all__'
         

class ArticleForm(forms.ModelForm):
    #edition = forms.ModelChoiceField(label='版別',queryset=Edition.objects.all())
    title = forms.CharField(label='標題', max_length=128)
    content = forms.CharField(label='內容', widget=forms.Textarea)

    class Meta:
        model = Article
        fields = ['title', 'content']


class CommentForm(forms.ModelForm):
    content = forms.CharField(label='內容', widget=forms.Textarea)

    class Meta:
        model = Comment
        fields = ['content']

theWaster/edition/views.py
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.template.context_processors import request

from account.models import UserProfile
from edition.forms import EditionForm, SortForm, ArticleForm
from edition.models import Edition, Sort, Article


sorts = Sort.objects.all()
editions = Edition.objects.all()

def sortEdition(request):
    
    return render(request, 'edition/sortEdition.html') 



def article(request, editionId):
    articleList = Article.objects.filter(edition=editionId)
    
    return render(request, 'edition/article.html', {'articleList':articleList, 'editionId':editionId}) 

    
def sortCreate(request): 
    template = 'edition/sortCreate.html' 
    if request.method == 'GET': 
        return render(request, template, {'sortForm':SortForm()}) 
    # POST 
    sortForm = SortForm(request.POST) 
    if not sortForm.is_valid(): 
        return render(request, template, {'sortForm':SortForm}) 
    sortForm.save() 
    messages.success(request, '類別已新增\o/') 
    return redirect('edition:sortEdition') 


def editionCreate(request): 
    template = 'edition/editionCreate.html' 
    if request.method == 'GET': 
        return render(request, template, {'editionForm':EditionForm()}) 
    # POST 
    editionForm = EditionForm(request.POST) 
    if not editionForm.is_valid(): 
        return render(request, template, {'editionForm':editionForm}) 
    editionForm.save() 
    messages.success(request, '版域已新增\o/') 
    return redirect('edition:sortEdition') 


def articleCreate(request):#未完成
    template = 'edition/articleCreate.html' 
    if request.method == 'GET': 
        return render(request, template, {'articleForm':ArticleForm()}) 
    # POST 
    articleForm = ArticleForm(request.POST) 
    if not articleForm.is_valid(): 
        return render(request, template, {'articleForm':articleForm}) 
    articleForm.save() 
    messages.success(request, '發文成功') 
    return redirect('edition:sortEdition') 


def sortUpdate(request,sortId): #考慮不使用
    template = 'edition/sortUpdate.html' 
    sort = get_object_or_404(Sort,id=sortId) 
    #POST
    sortForm = SortForm(request.POST, instance=sort) 
    if not sortForm.is_valid(): 
        return render(request, template, {'sortForm':sortForm}) 
    sortForm.save() 
    messages.success(request, '修改成功')  
    return redirect('edition:sortEdition') 


def editionUpdate(request,editionId): #考慮不使用
    template = 'edition/editionUpdate.html' 
    edition = get_object_or_404(Edition,id=editionId) 
    #POST
    editionForm = EditionForm(request.POST, instance=edition) 
    if not editionForm.is_valid(): 
        return render(request, template, {'editionForm':editionForm}) 
    editionForm.save() 
    messages.success(request, '修改成功')  
    return redirect('edition:sortEdition') 

theWaster/edition/templates/edition/article.html
{% extends "main/templates.html" %}
{% load staticfiles %}
{% block css %}
<link rel=stylesheet href="{% static 'edition/css/article.css' %}">
{% endblock %}
{% block content %}

<div id=articleBtn>
  <a href="{% url 'edition:sortCreate' %}">新增類別</a> 
  <a href="{% url 'edition:editionCreate' %}">新增版</a>
  <a href="{% url 'edition:articleCreate' %}">發文</a>
</div>
  <h1 style="color:red;">{{ editionId }}</h1>
 <div class=clear></div>
  {% for article in articleList %}  
  <div id=article>
  <div id=articleAccount>
  <div id=articleHead><img src="{{ article.user.image }}"></div>
  <div id=articleUser>{{ article.user }}</div>
  </div>
  <div id=articleTitle>{{ article.title }}</div>
  <div id=articleDateTime>{{ article.dateTime }}</div>
  <div id=articleContent>{{ article.content }}</div>
  <div class=clear></div>
  </div>
  {% endfor %}
<br><br>
{% endblock %}

theWaster/edition/templates/edition/articleCreate.html
{% extends "main/templates.html" %}
{% load staticfiles %}
{% block css %}
<link rel=stylesheet href="{% static 'edition/css/sort.css' %}">
{% endblock %}
{% block content %}
<h1>發文</h1> 
  <form method="post" action="{% url 'edition:articleCreate' %}">  
    {% csrf_token %}  
    {{ articleForm.as_p }}
    <input type="submit" name="" value="新增">  
    <a href="{% url 'edition:sortEdition' %}">放棄</a> 
  </form>  
{% endblock %}

theWaster/edition/templates/edition/editionCreate.html
{% extends "main/templates.html" %}
{% load staticfiles %}
{% block css %}
<link rel=stylesheet href="{% static 'edition/css/edition.css' %}">
{% endblock %}
{% block content %}
<h1>新增版</h1> 
  <form method="post" action="{% url 'edition:editionCreate' %}">  
    {% csrf_token %}  
    {{ editionForm.as_p }}
    <input type="submit" name="" value="新增">  
    <a href="{% url 'edition:sortEdition' %}">放棄</a> 
  </form>  
{% endblock %}

theWaster/edition/templates/edition/sortCreate.html
{% extends "main/templates.html" %}
{% load staticfiles %}
{% block css %}
<link rel=stylesheet href="{% static 'edition/css/sort.css' %}">
{% endblock %}
{% block content %}
<h1>新增類別</h1> 
  <form method="post" action="{% url 'edition:sortCreate' %}">  
    {% csrf_token %}  
    {{ sortForm.as_p }}
    <input type="submit" name="" value="新增">  
    <a href="{% url 'edition:sortEdition' %}">放棄</a> 
  </form>  
{% endblock %}

theWaster/edition/templates/edition/sortEdition.html
{% extends "main/templates.html" %}
{% load staticfiles %}
{% block css %}
<link rel=stylesheet href="{% static 'edition/css/sort.css' %}">
{% endblock %}
{% block content %}
<div id=btn>
  <a class=btn href="{% url 'edition:sortCreate' %}">新增類別</a> 
  <a class=btn href="{% url 'edition:editionCreate' %}">新增版</a>
  <div class=clear></div> 
</div>
<div class=clear></div> 
<br>
  <div id=allSort>
  {% for sort in SORT %}
  <div id=sort>
  <div id=sortName><p>{{ sort.sort }}</p></div>
    {% for edition in EDITION %}
      {% if edition.sort == sort %}
      <div id=editionName><p>{{ edition.edition }}</p></div>
      {% endif %}
    {% endfor %}
  </div>
  {% endfor %}
  <div class=clear></div>
  </div><br><br>
{% endblock %}